# Generated by Django 4.2 on 2024-10-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('countries', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('result_message', models.TextField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ('-created_at',),
            },
        ),
    ]
